# Generated by Django 6.0.6 on 2026-09-25 16:58
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment'),  # اگر اسم فایل مایگریشن قبلی شما چیز دیگری است (مثلاً 0007_auto_...)، آن را اینجا بنویسید
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
            preserve_default=False,
        ),
    ]
