# Generated by Django 6.0.6 on 2026-09-28 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_add_post_to_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_date']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='massage',
            new_name='message',
        ),
    ]
